springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true
    swagger-ui:
      base-url: /documentacion
swagger:
  base-package: 'com.umdev.commons'
  api-info:
    title: 'UMDEV Commons'
    description: 'Commons library for UMDEV projects'
    contact:
      name: 'Luis Antonio Mata'
      url: 'www.prx.test'
      email: 'luis.antonio.mata@gmail.com'

security:
  discovery:
    client:
      name: prx-backbone-rest
      trust-store-file: prx_backbone_rest.jks
      trust-store-password: prx-backbone-rest
      max-total-connections: 10
      max-connections-per-host: 10
